### ISSUE TITLE
Print full package name or better file name and line of implementer's definition

### ISSUE THREAD

**Issue by least-olegs** [dominikh/implements#12]
Right now the output isn't terribly useful since it only gives the name of the implementer, but finding the definition of the implementer is kind of challenging (one needs to look up each matched package given with the `-interfaces`, then find what actual files map to those packages, then do a regex search for something that looks like the definition of the implementer in those files).

**Comment by dominikh** [comment]
`implements` is more of an educational tool, to discover types in the standard library. The usual workflow would be to look up the types in godoc, not find their exact code location.

Your use case sounds a lot more like what one would use the Go Oracle for.

**Comment by least-olegs** [comment]
Well, it's tedious, but I could write a script to do source lookups. The problem is that if you just give the name of the type and the last word in the package name: this is not enough information to identify the implementer. If you have two packages providing `conf.Config` (and the reality of the situation is that in a non-trivial project there are about a dozen of packages with such inventive names), then finding the one you are actually looking for becomes impossible (unless you generate some Go code to test all of them by trying to compile them).

**Comment by dominikh** [comment]
> The problem is that if you just give the name of the type and the last word in the package name: this is not enough information to identify the implementer

That'd be a bug. For standard library types, we print the whole import path, not just the package name. Apparently, we aren't doing the same for non-stdlib packages. We probably should.

> Well, it's tedious, but I could write a script to do source lookups

Like I said before, I don't think you should be using `implements` for this in the first place, but instead use the Go Oracle (now called guru), which supports an "implements" query and gives you proper, machine-parseable location data. See https://docs.google.com/document/d/1SLk36YRjjMgKqe490mSRzOPYEDe0Y_WQNRv-EiFYUyw/view for more information.

`implements` has more than one UI decision making it unsuitable for programmatic use.
